### ISSUE TITLE
Add to F-Droid

### ISSUE THREAD

**Issue by pizzamaker** [rmanor/currentwidget#57]
F-Droid is a FOSS catalog of Android apps. It would be brilliant to have this app available there!

**Comment by est31** [comment]
In fact, its already inside f-droid https://f-droid.org/repository/browse/?fdid=com.manor.currentwidget

The fdroid entry still points to the old repo location at google though, I'll send a merge request to update it to the fdroiddata repo.

@pizzamaker you can close this issue

**Comment by pizzamaker** [comment]
Thanks!
